BunkPlanner/BunkPlanner/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('accounts.urls')),
]

BunkPlanner/accounts/urls.py
from django.conf.urls import url
from . import views



app_name='accounts'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^signup/$',views.signup,name='signup'),
    url(r'^login/$',views.login,name='login'),
    url(r'^dashboard/$',views.dashboard,name='dashboard'),

]

BunkPlanner/accounts/models.py
from django.db import models

# Create your models here.

BunkPlanner/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import validate_email


class SignUpForm(forms.ModelForm):
    username=forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control','placeholder':'Username'}),required=True)
    first_name=forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control','placeholder':'First Name'}),required=True,max_length=20)
    last_name=forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control','placeholder':'Last Name'}),required=True,max_length=20)
    email=forms.CharField(widget=forms.EmailInput(attrs={'class' : 'form-control','placeholder':'Email'}),required=True)
    password=forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'form-control','placeholder':'Password'}),required=True)
    password2=forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'form-control','placeholder':'Confirm Password'}),required=True)

    class Meta:
        model=User
        fields=('username','first_name','last_name','email','password','password2')


    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            match=User.Objects.get(username=username)
        except:
            return self.cleaned_data['username']
        raise forms.ValidationError("Username already exist")
    #
    # def clean_email(self):
    #     email = self.cleaned_data['email']
    #     if User.Objects.filter(email=email).exists():
    #         raise forms.ValidationError("email already exist")
    #     return email
    #     # except:
    #     #     return self.cleaned_data['email']
    #     # raise forms.ValidationError("email already exist")


    def clean_password2(self):
        pas=self.cleaned_data['password']
        pas2=self.cleaned_data['password2']
        MIN_LENGTH=8
        if pas and pas2:
            if pas!=pas2:
                raise forms.ValidationError("Password Not Matched")
            else:
                if len(pas)<MIN_LENGTH:
                    raise forms.ValidationError("Password Short.Minimum 8 characters long")

BunkPlanner/accounts/views.py
from django.shortcuts import render,redirect
from accounts.forms import SignUpForm
from django.contrib import auth
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User
from django.contrib import messages


def index(request):
    return render(request,'accounts/index.html')


def dashboard(request):
    return render(request,'accounts/dashboard.html')



def signup(request):

    if request.method=="POST":
        form=SignUpForm(request.POST)
        if form.is_valid():
            username=form.cleaned_data['username']
            first_name=form.cleaned_data['first_name']
            last_name=form.cleaned_data['last_name']
            email=form.cleaned_data['email']
            password=form.cleaned_data['password']
            User.objects.create_user(username=username,first_name=first_name,last_name=last_name,email=email,password=password)
            usr=auth.authenticate(username=username,password=password)
            auth.login(request,usr)
            return redirect('accounts:dashboard')
        else:
            return render(request,'accounts/signupform.html',{'form':form})
    else:
        form=SignUpForm()

    return render(request,'accounts/signupform.html',{'form':form})



def login(request):
    if request.method=="POST":
        username=request.POST['username']
        password=request.POST['password']
        try:
            user=auth.authenticate(username=username,password=password)
            if user is not None:
                auth.login(request,user)
                return redirect('accounts:dashboard')
            else:
                messages.error(request,"Username and password not matched")

        except auth.ObjectDoesNotExist:
            return render(request,'accounts/login.html')

BunkPlanner/accounts/templates/accounts/dashboard.html
<h1>Welcome {{ request.user.first_name }}</h1>

BunkPlanner/accounts/templates/accounts/index.html

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Bunk Planner</title>

    <!-- Bootstrap core CSS -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
    integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <!-- Custom styles for this template -->
    <link href="{% static 'accounts\index.css' %}" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
      <a class="navbar-brand" href="#">Bunk Planner</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarsExampleDefault" >
        <ul class="navbar-nav mr-auto ">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#" >Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>

      </div>
      <div class="pull-right" style="display: inline-flex;">
        <div style="margin: 5px">
       <button type="button" class="btn btn-success login"><a href="{% url 'accounts:login' %}" style="color:#2ec866">Log In</a></button>
       </div>
        <div style="margin: 5px">
       <button type="button" class="btn btn-success signup"><a href="{% url 'accounts:signup' %}">Sign Up</a></button>
        </div>
      </div>
    </nav>

    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)),url('{% static "accounts/images/back7.jpeg" %}');">
        <div class="container jumbContainer">
          <h1 class="display-3">Hello, People!</h1>
          <p>Plan Your Bunk Efficiently and Effectively</p>
          <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
        </div>
      </div>

      <div class="container content" >
        <!-- Example row of columns -->
        <div class="row">
          <div class="col-sm-4 col-xs-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
          <div class="col-sm-4 col-xs-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
          <div class="col-sm-4 col-xs-4">
            <h2>Heading</h2>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
        </div>

        <hr>

      </div> <!-- /container -->

    </main>

    <footer class="container">
      <p>&copy; Company 2017</p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>


   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

BunkPlanner/accounts/templates/accounts/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Jumbotron Template for Bootstrap</title>

    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static 'accounts/login.css' %}" rel="stylesheet">
  </head>

  <body>



<div class ="container" style="border:1px solid black">
     <div class="xyz">
       {% if messages %}
       <div class ="row">
         <div class="col-md-12">
           {% for message in messages %}
           <div class="alert alert-danger alert-dismissible fade show" role="alert">
              <strong>Oops!   </strong>{{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
          </div>
           {% endfor %}
         </div>
       </div>
       {% endif %}
        <div class="top">
          <div class="row top_row">
            <div class="col-sm-9 head">
                <h4>Login</h4>
                <p>See what new bunks are happening</p>
            </div>
            <div class="col-sm-3 head_icon">
                <i class="fa fa-sign-in fa-3x" aria-hidden="true"></i>
            </div>
          </div>
        </div>


        <div class="below_head">

 <form style="margin:5px;padding-top: 20px" method="post" action="">
        {% csrf_token %}
        <div class="form_content">
                        <div class="inner-addon left-addon">
                            <i class="fa fa-user" aria-hidden="true"></i>
                            <input type="text" name="username" class ="form-control" placeholder="Username">
                        </div>

                        <div class="inner-addon left-addon">
                            <i class="fa fa-key" aria-hidden="true"></i>
                            <input type="password" name="password" class="form-control" placeholder="Password">
                        </div>

                        <button type="submit" class="btn btn-success btn-block">Login</button>

          </div>
</form>
<div class="forgot_password_link">
<p><a href="#">Forgot Password?</a></p>
</div>
        </div>
     </div>

</div>



<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>


   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

BunkPlanner/accounts/templates/accounts/signupform.html

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Jumbotron Template for Bootstrap</title>


    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static 'accounts/signupform.css' %}" rel="stylesheet">
  </head>

  <body>

<div class ="container" style="border:1px solid black">
     <div class="xyz">
        <div class="top">
          <div class="row top_row">
            <div class="col-sm-9 head">
                <h4>Signup</h4>
                <p>Be a part of bunk planner</p>
            </div>
            <div class="col-sm-3 head_icon">
               <i class="fa fa-user-plus fa-3x" aria-hidden="true"></i>
            </div>
          </div>
        </div>


        <div class="below_head">

 <form style="margin:5px;padding-top: 20px" method="post" action="{% url 'accounts:signup' %}">
        {% csrf_token %}
        <div class="form_content">
                        <div class="inner-addon left-addon">
                            <i class="fa fa-user" aria-hidden="true"></i>
                            {{ form.username }}
                            {{ form.username.errors }}
                        </div>

                        <div class="inner-addon left-addon">
                            <i class="fa fa-user-o" aria-hidden="true"></i>
                            {{ form.first_name }}
                            {{ form.first_name.errors }}
                        </div>
                        <div class="inner-addon left-addon">
                            <i class="fa fa-user-o" aria-hidden="true"></i>
                            {{ form.last_name }}
                            {{ form.last_name.errors }}

                        </div>
                        <div class="inner-addon left-addon">
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                            {{ form.email }}
                            {{ form.email.errors }}
                        </div>
                        <div class="inner-addon left-addon">
                            <i class="fa fa-key" aria-hidden="true"></i>
                            {{ form.password }}
                            {{ form.password.errors }}
                        </div>
                        <div class="inner-addon left-addon">
                            <i class="fa fa-key" aria-hidden="true"></i>
                            {{ form.password2 }}
                            {{ form.password2.errors }}
                        </div>
                        <div class="signup_btn">
                        <button type="submit" class="btn btn-danger btn-block">Signup</button>
                        </div>


   
</form>

        </div>
     </div>

</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>


   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>